name: Deploy T-shop Infra with Bicep

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

env:
  RESOURCE_GROUP: Online-cornerRG
  LOCATION: eastus

jobs:
  deploy-infra:
    name: Deploy Infra to Azure
    runs-on: self-hosted  # must be on an Azure VM or App with the UAMI assigned

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure using UAMI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MANAGED_IDENTITY_CLIENT_ID }}
          enable-managed-identity: true
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./infra/main.bicep
          parameters: ./infra/parameters.json
          deploymentName: tshop-deployment-${{ github.run_number }}
